version: '3.4'
services:
  liberland-node.avado.dappnode.eth:
    build: ./build
    image: 'liberland-node.avado.dappnode.eth:0.0.2'
    restart: always
    volumes:
      - 'data:/data'
    ports:
      - '12345:12345'
      - '12345:12345/UDP'
volumes:
  data: {}
